---
driver:
  name: dokken

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec
  sudo: true

platforms:
- name: ubuntu
  driver:
    image: ubuntu:14.04

suites:
  - name: default
    run_list:
      - recipe[os_prepare]
  - name: profile
    run_list:
      - recipe[os_prepare]
  - name: contains_inspec
    run_list:
      - recipe[os_prepare]
    inspec_tests:
      - https://github.com/nathenharvey/tmp_compliance_profile
