language: ruby

rvm:
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3
  - ruby-head

before_install: gem install bundler -v 1.10.6
bundler_args: --without guard

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head
