---
sudo: required
language: ruby
cache: bundler

# necessary for docker to work
dist: trusty
services:
  - docker

rvm:
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3
  - ruby-head

bundler_args: --without guard integration

before_install:
  - gem update --system 2.4.5
  - gem --version

matrix:
  include:
    - rvm: 1.9.3
      gemfile: Gemfile
    - rvm: 2.0
      gemfile: Gemfile
    - rvm: 2.1
      gemfile: Gemfile
    - rvm: 2.2
      gemfile: Gemfile
    - rvm: ruby-head
      gemfile: Gemfile
  allow_failures:
    - rvm: ruby-head
